import gleam/dict.{type Dict}

pub fn get_projects() -> Dict(String, String) {
  dict.from_list([
    #("ravioli-ravioli", "<h1 id=\"Ravioli-Ravioli\">Ravioli, Ravioli</h1>\n<p>A funny PC game about hitting clients in an italian restaurant.</p>\n<h2 id=\"Gameplay\">Gameplay</h2>\n<p>Serve customers quickly while maintaining quality in a chaotic kitchen environment. Balance speed with customer satisfaction!</p>\n<h3 id=\"Game-Mechanics\">Game Mechanics</h3>\n<ul>\n<li>\nTime management challenges\n</li>\n<li>\nCustomer satisfaction system\n</li>\n<li>\nUpgrade your kitchen equipment\n</li>\n<li>\nUnlock new recipes\n</li>\n</ul>\n<h2 id=\"Technologies\">Technologies</h2>\n<ul>\n<li>\nUnity Engine for game development\n</li>\n<li>\nC# Programming for game logic\n</li>\n<li>\nCustom AI System for customer behavior\n</li>\n<li>\nHand-drawn art style\n</li>\n</ul>\n<h2 id=\"Story\">Story</h2>\n<p>You play as a chef in a bustling Italian restaurant where things don&#39;t always go according to plan. Keep your customers happy (or hit them with ravioli when they&#39;re too demanding)!</p>\n<h2 id=\"Awards\">Awards</h2>\n<ul>\n<li>\nBest Humor in Gaming 2024\n</li>\n<li>\nIndie Game Festival Finalist\n</li>\n</ul>\n"),
    #("the-flying-rocket", "<h1 id=\"The-Flying-Rocket\">The Flying Rocket</h1>\n<p id=\"mobile-images\"><img alt=\"Gif\" src=\"/kiss.gif\">\n<img alt=\"Gif\" src=\"/kiss.gif\">\n<img alt=\"Gif\" src=\"/kiss.gif\">\n<img alt=\"Gif\" src=\"/kiss.gif\"></p>\n<p>An arcade mobile game about infiltrating a mothership with innovative controls based on forces. Hola</p>\n<h2 id=\"Features\">Features</h2>\n<ul>\n<li>\nPhysics-based controls that respond to real force inputs\n</li>\n<li>\nChallenging gameplay with progressive difficulty\n</li>\n<li>\nMobile-optimized interface for touch controls\n</li>\n<li>\nBeautiful space-themed graphics\n</li>\n</ul>\n<h2 id=\"Development\">Development</h2>\n<p>Built using Unity and C# with a custom physics engine designed specifically for mobile devices.</p>\n<h3 id=\"Technical-Details\">Technical Details</h3>\n<p>The game uses:\n- Custom force-based input system\n- Procedurally generated levels\n- Optimized rendering for mobile platforms</p>\n<h2 id=\"Download\">Download</h2>\n<p>Available on iOS and Android platforms.</p>\n"),
    #("the-wizards-tower", "<h1 id=\"The-Wizard's-Tower\">The Wizard&#39;s Tower</h1>\n<p>A simple 2D platformer for PC with a challenging mouse input twist.</p>\n<h2 id=\"Concept\">Concept</h2>\n<p>Navigate through a mystical tower using unconventional mouse-based controls. The wizard&#39;s tower is full of magical challenges and platforming puzzles.</p>\n<h2 id=\"Features\">Features</h2>\n<ul>\n<li>\nPixel art graphics with retro charm\n</li>\n<li>\nInnovative control scheme using mouse movements\n</li>\n<li>\nChallenging platforming mechanics\n</li>\n<li>\nProgressive difficulty through tower levels\n</li>\n</ul>\n<h2 id=\"Gameplay-Mechanics\">Gameplay Mechanics</h2>\n<ul>\n<li>\nMouse-driven character movement\n</li>\n<li>\nPhysics-based jumping and climbing\n</li>\n<li>\nCollectible magical artifacts\n</li>\n<li>\nHidden secrets in each level\n</li>\n</ul>\n<h2 id=\"Art-Style\">Art Style</h2>\n<p>Beautiful pixel art inspired by classic platformers with a magical twist. Each floor of the tower has its own unique theme and color palette.</p>\n<h2 id=\"Development-Status\">Development Status</h2>\n<p>Currently in beta testing. Expected release Q2 2025.</p>\n"),
  ])
}
